coco_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: yh31686
      user: ERAD929
      role: ETL_USER
      database: COCO_DB
      warehouse: VW_COCO
      schema: PUBLIC
      threads: 4
      authenticator: externalbrowser
