{{
    config(
        materialized='view',
        database='COCO_DB',
        schema='GOLD'
    )
}}

SELECT
    SALES_SK AS SALES_KEY,
    ORDERNUMBER AS ORDER_NUMBER,
    ORDERLINENUMBER AS ORDER_LINE_NUMBER,
    PRODUCT_SK AS PRODUCT_KEY,
    CUSTOMER_SK AS CUSTOMER_KEY,
    DATE_SK AS DATE_KEY,
    ORDER_STATUS_SK AS ORDER_STATUS_KEY,
    QUANTITYORDERED AS QUANTITY_ORDERED,
    PRICEEACH AS UNIT_PRICE,
    SALES AS TOTAL_SALES_AMOUNT
FROM {{ ref('fact_sales') }}
